Jysk2_0/Models/RecalcViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jysk2_0.Models
{

    //Recalc test
    public class RecalcViewModel
    {
        [Display(Name="Selections", ResourceType=typeof(Resources.Resources))]
        public int SelectedColorId { get; set; }
        public SelectList Colors { get; set; }
        public SelectList PaperTypes { get; set; }
        public SelectList ColumnWidths { get; set; }
    }
}

Jysk2_0/Controllers/PapersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Jysk2_0.ToastrHelper;
using Jysk2_0.Models;
using Jysk2_0.Attributes;
using Utils;
using Jysk2_0.Proxy;

namespace Jysk2_0.Controllers
{
    public class PapersController : AbstractMessageController
    {
        private JyskDBEntities db = new JyskDBEntities();

        // GET: Papers
        public ActionResult Index()
        {
            List<Paper> papers =  new PapersProxy().ReadAll().ToList();
            PaperListViewModel viewModel = new PaperListViewModel();
            viewModel.PaperSelectedList = papers.Select(x => new PaperSelectedViewModel() { Paper = x }).ToList();
            return View(viewModel);
        }

        // GET: Papers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paper paper = await db.Papers.FindAsync(id);
            if (paper == null)
            {
                return HttpNotFound();
            }
            return View(paper);
        }
        [AccessDeniedAuthorizeAttribute(Roles = "Admin")]
        // GET: Papers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Papers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AccessDeniedAuthorizeAttribute(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Name,Amount,Readers,PricePrMM")] Paper paper)
        {
            if (ModelState.IsValid)
            {
                var ost = MyUtilsNiceness.ConvertString("ost");

                new PapersProxy().Add(paper);
                this.AddToastMessage("Congratulations", "Paper is created", ToastType.Success);
                return RedirectToAction("Index");
            }

            return View(paper);
        }

        // GET: Papers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paper paper = await db.Papers.FindAsync(id);
            if (paper == null)
            {
                return HttpNotFound();
            }
            return View(paper);
        }

        // POST: Papers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Amount,Readers,PricePrMM")] Paper paper)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paper).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(paper);
        }

        // GET: Papers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paper paper = await db.Papers.FindAsync(id);
            if (paper == null)
            {
                return HttpNotFound();
            }
            return View(paper);
        }

        // POST: Papers/Delete/5
        [HttpPost, ActionName("Delete")]
        public JavaScriptResult DeleteConfirmed(int id)
        {
            Paper paper = db.Papers.Find(id);
            this.AddToastMessage("Congratulations", "You have deleted the paper!!!", ToastType.Success);
            db.Papers.Remove(paper);
            db.SaveChanges();
            return JavaScript("location.reload(true)");
        }

        [HttpPost]
        public async Task<ActionResult> ReCalculate(string ids, string strSelected)
        {
            this.AddToastMessage("Congratulations", "You made it all the way here!", ToastType.Success);
            RecalcViewModel viewModel = new RecalcViewModel();
            List<Color> colors = await db.Colors.ToListAsync();
            int parsedValue = 0;

            if (Int32.TryParse(strSelected, out parsedValue))
            {
                viewModel.Colors = new SelectList(colors, "Id", "Name", new { id = parsedValue });
                viewModel.SelectedColorId = parsedValue;
            }
            else
            {
                viewModel.Colors = new SelectList(colors, "Id", "Name");
            }
            viewModel.ColumnWidths = new SelectList(await db.ColumnWidths.ToListAsync(), "Id", "ColumnWidthString");
            viewModel.PaperTypes = new SelectList(await db.PaperTypes.ToListAsync(), "Id", "Name");

            ViewBag.Id = ids;
            return PartialView("_Recalc", viewModel);

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jysk2_0/Views/Papers/Index.cshtml
@model Jysk2_0.Models.PaperListViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (@User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<div class="col-md-7">
    <table class="table" id="cb-table">
        <tr>
            <th>
                @Resources.Resources.Selections
            </th>
            <th>
                Aviser
            </th>
            <th>
                Oplag
            </th>
            <th>
                Læsere
            </th>
            <th>

            </th>
        </tr>

        @foreach (var item in Model.PaperSelectedList)
        {
            <tr>
                <td>
                    @Html.CheckBoxFor(modelItem => item.Selected, new { @class="IdChecked", @id=@item.Paper.Id})
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paper.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paper.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paper.Readers)
                </td>
                <td>
                    <a id="deleteItem" class="deleteItem" data-target="#basic" data-toggle="modal" data-id="@item.Paper.Id">Delete</a>
                </td>
            </tr>
        }

    </table>
</div>

<div id="recalcvalue" class="col-md-4"></div>

<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                <button id="btnContinueDelete" type="button" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
<script type="text/javascript">
    //Recalc JS
    $('.IdChecked').click(function() {
        var tableRow = $(this).parent().parent();
        var id = $(this).attr('id');
        var strSelected = "";
        $("#ddl option:selected").each(function () {
            strSelected += $(this)[0].value;
        });
        var arrayIds = [];
        $("#cb-table input:checkbox:checked").each(function () {
            arrayIds.push(this.id);
        });
        $.ajax({
            data: { "ids": JSON.stringify(arrayIds), "strSelected": strSelected },
            datatype: "json",
            type: "POST",
            url: '@Url.Action("ReCalculate", "Papers")',
            cache: false,
            success: function (data) {
                $('#recalcvalue').html(data);
            }
        });
    });


    //Delete modal JS
    var item_to_delete;
    $(".deleteItem").click(function (e) {
        item_to_delete = $(this).data('id');
    });
    $('#btnContinueDelete').click(function () {
        $.post('@Url.Action("Delete", "Papers")', { id: item_to_delete })
        .done(function (data) {
            $('#basic').modal('hide');
            window.location.href = '@Url.Action("Index", "Papers")';
        });
    });
</script>
    
}

Jysk2_0/Views/Papers/_Recalc.cshtml
@model Jysk2_0.Models.RecalcViewModel

@ViewBag.Id -- Here!!


<div class="col-md-4">
    @Html.DropDownListFor(n => n.SelectedColorId,
                Model.Colors,
                "Vælg farve", new { @id= "ddl", @class= "dropdown" })
    @Html.DropDownListFor(m => m.ColumnWidths,
                Model.ColumnWidths,
                "Vælg spaltebredde og højde (mm)")
    @Html.DropDownListFor(m => m.PaperTypes,
                Model.PaperTypes,
                "Vælg spaltebredde og højde (mm)")
</div>

@Html.Partial("_Toastr")

    <script type="text/javascript">
        $(document).ready(function() {
            $("#ddl").change(function() {
                var strSelected = "";
                $("#ddl option:selected").each(function() {
                    strSelected += $(this)[0].value;
                });
                var arrayIds = [];
                $("#cb-table input:checkbox:checked").each(function () {
                    arrayIds.push(this.id);
                });
                $.ajax({
                    data: { "ids": JSON.stringify(arrayIds), "strSelected": strSelected },
                    datatype: "json",
                    type: "POST",
                    url: '@Url.Action("ReCalculate", "Papers")',
                    cache: false,
                    success: function (data) {
                        $('#recalcvalue').html(data);
                    }
                });
            });
        });
    </script>    